options(tz="Europe/Berlin")
install.packages("tzdb", repos= "https://cloud.r-project.org/", dependencies = TRUE, lib="R_libs")
install.packages("zoo", repos= "https://cloud.r-project.org/", dependencies = TRUE, lib="R_libs")
install.packages("xts", repos= "https://cloud.r-project.org/", dependencies = TRUE, lib="R_libs")
install.packages("stringr", repos= "https://cloud.r-project.org/", dependencies = TRUE, lib="R_libs")
install.packages("fs", repos= "https://cloud.r-project.org/", dependencies = TRUE, lib="R_libs")
install.packages("crayon", repos= "https://cloud.r-project.org/", dependencies = TRUE, lib="R_libs")
install.packages("readr", repos= "https://cloud.r-project.org/", dependencies = TRUE, lib="R_libs")
install.packages("jsonlite", repos= "https://cloud.r-project.org/", dependencies = TRUE, lib="R_libs")
