# This is a basic workflow that is manually triggered on uses linux

name: Manual data update

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-data:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Berlin
      TK_USER: ${{ secrets.TK_USER }}
      TK_PASS: ${{ secrets.TK_PASS }}
    steps:
      - name: Checkout latest version
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install -r requirements.txt
      - name: Generate data
        run: python scripts/generate_data.py
      - name: Configure git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Commit data changes
        run: |
          git add data data2
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Manual data update"
          git push origin master
