# This is a basic workflow that is manually triggered

name: Manual install test

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  installieren:
    runs-on: ubuntu-latest
    steps:
      - name: Installiere notwendige Pakete 
        run:  |
          R -e 'install.packages("zoo")'
          R -e 'install.packages("xts")'
          R -e 'install.packages("stringr")'
          R -e 'install.packages("fs")'
          R -e 'install.packages("readr")'
          R -e 'install.packages("jsonlite")'
