# This is a basic workflow that is manually triggered

name: Manual install test

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  installieren:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest version
        uses: actions/checkout@v2
      - name: Installiere notwendige Pakete 
        run:  |
          mkdir R_libs
          export R_LIBS_USER="R_libs"
          R -e 'install.packages("zoo", lib="R_libs")'
          R -e 'install.packages("xts", lib="R_libs")'
          R -e 'install.packages("stringr", lib="R_libs")'
          R -e 'install.packages("fs", lib="R_libs")'
          R -e 'install.packages("readr", lib="R_libs")'
          R -e 'install.packages("jsonlite", lib="R_libs")'
      - name: Teste notwendige Pakete
        run: |
           R -e 'library("zoo")'
           echo $R_LIBS_USER
