# This is a basic workflow that is manually triggered

name: Manual execution

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  installieren:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest version
        uses: actions/checkout@v2
      - name: List files
        run: ls -lah
      - name: Installiere notwendige Pakete 
        run:  |
          sudo apt-get install -y tzdata
          mkdir R_libs
          export R_LIBS_USER="R_libs"
          R -e 'install.packages("tzdb", dependencies = TRUE, lib="R_libs")'
          R -e 'install.packages("zoo", dependencies = TRUE, lib="R_libs")'
          R -e 'install.packages("xts", dependencies = TRUE, lib="R_libs")'
          R -e 'install.packages("stringr", dependencies = TRUE, lib="R_libs")'
          R -e 'install.packages("fs", dependencies = TRUE, lib="R_libs")'
          R -e 'install.packages("crayon", dependencies = TRUE, lib="R_libs")'
          R -e 'install.packages("tidyverse", dependencies = TRUE, lib="R_libs")'
          R -e 'install.packages("jsonlite", dependencies = TRUE, lib="R_libs")'
      - name: Führe Analyse Batch aus
        run: Rscript calculation2.r # Test libs -e 'library("zoo", lib.loc="R_libs")'
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"    # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.email "<>"
      - name: commit update
        run: |
          git add data2
          git commit -m "Daily Update."
          git push origin master    # Stage the file, commit and push
